services:
  django-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gym-workout-planner-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - ./backend/.env
    depends_on:
      postgres-db:
        condition: service_healthy
        restart: true
  postgres-db:
    image: postgres:18-bookworm
    container_name: postrgres-db
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
# docker compose up --build
# Base Debian estable, incluye herramientas completas,
# buen equilibrio entre peso y compatibilidad. Ideal para debugging y uso local.
