# Generated by Django 5.2.7 on 2025-10-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="video_url",
        ),
    ]
