# Generated by Django 5.2.7 on 2025-10-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
        ("routines", "0002_remove_exercise_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="exercises.exercise"
            ),
        ),
        migrations.DeleteModel(
            name="Exercise",
        ),
    ]
